spring.application.name=TCC

# Desliga logs do Spring no arquivo
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR

logging.level.com.example=INFO
logging.file.name=logs/app.log

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tccumcriqedmat@gmail.com
spring.mail.password=bhgd vxqe rpiy vzyx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
