spring.application.name=TCC

spring.config.import=optional:file:.env[.properties]

# Configurações de banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SMTP
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
spring.mail.properties.mail.debug=true


# Desliga logs do Spring no arquivo
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.example=INFO
logging.file.name=logs/app.log

server.port=${PORT:8080}